export enum FRETAMENTO_EVENTUAL_SITUACAO_ENUM {
    ORCAMENTO_CONTATO = 'ORCAMENTO_CONTATO',
    ORCAMENTO_CLIENTE = 'ORCAMENTO_CLIENTE',
    NAO_CONTRATADO_CONTATO = 'NAO_CONTRATADO_CONTATO',
    NAO_CONTRATADO_CLIENTE = 'NAO_CONTRATADO_CLIENTE',
    CONTRATADO = 'CONTRATADO'
}
